apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk2tg
  labels:
    app: vk2tg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vk2tg
  template:
    metadata:
      labels:
        app: vk2tg
    spec:
      containers:
        - name: app
          image: "vk2tg:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "128Mi"
              cpu: "300m"
