{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vk2tg.fullname" . }}
  labels:
    {{- include "vk2tg.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: "vk2tg.bmstr.ru"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vk2tg.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
  tls:
    - hosts:
      - vk2tg.bmstr.ru
{{- end }}
