apiVersion: v1
kind: Service
metadata:
  name: vk2tg
  labels:
    app: vk2tg
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vk2tg