apiVersion: v1
kind: Secret
metadata:
  name: vk2tg-secret
type: Opaque
stringData:
  VK_GROUP_ID: "{{ .Values.VK_GROUP_ID }}"
  TG_BOT_TOKEN: "{{ .Values.TG_BOT_TOKEN }}"
  TG_CHANNEL_ID: "{{ .Values.TG_CHANNEL_ID }}"
