apiVersion: v1
kind: Secret
metadata:
  name: vk2tg-secret
type: Opaque
stringData:
  VK_GROUP_ID: "{{ .Values.VK_GROUP_ID }}"
  TG_BOT_TOKEN: "{{ .Values.TG_BOT_TOKEN }}"
  TG_CHANNEL_ID: "{{ .Values.TG_CHANNEL_ID }}"
  TG_THREAD_ID: "{{ default "" .Values.TG_THREAD_ID }}"
  DB_HOST: "{{ .Values.DB_HOST }}"
  DB_PORT: "{{ .Values.DB_PORT }}"
  DB_USERNAME: "{{ .Values.DB_USERNAME }}"
  DB_PASSWORD: "{{ .Values.DB_PASSWORD }}"
  DB_DATABASE: "{{ .Values.DB_DATABASE }}"
  DB_SCHEMA: "{{ .Values.DB_SCHEMA }}"
