replicaCount: 1

image:
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:

resources: {}

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

env: []
