replicaCount: 1

image:
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: vk2tg.bmstr.ru
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - vk2tg.bmstr.ru

resources: {}

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

env: []
