replicaCount: 1

image:
  repository: vk2tg
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

env: []
